version: '3.9'

services:
  django:
    image: django-docker:0.0.1
    build: 
      context: ./api/
    ports: 
      - "8000:8000"
  
  react:
    image: react-docker:0.0.1
    build: 
      context: ./front-charllenge/
    ports:
      - "3000:3000"